# Stage 1: Build file JAR menggunakan Gradle dan JDK 17
FROM gradle:8.7-jdk17 AS build
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
# Menjalankan build fat JAR secara otomatis
RUN ./gradlew buildFatJar --no-daemon

# Stage 2: Menjalankan aplikasi dengan JRE yang super ringan
FROM openjdk:17-slim
EXPOSE 8080
RUN mkdir /app

# Menyalin file JAR spesifik milikmu dari Stage 1
COPY --from=build /home/gradle/src/build/libs/bpi-ktor-playground-all.jar /app/ktor-backend.jar

# Menjalankan Ktor backend
ENTRYPOINT ["java", "-jar", "/app/ktor-backend.jar"]