ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.bagaspardanailham.bpiktorplayground.SerializationKt.configureSerialization
      - com.bagaspardanailham.bpiktorplayground.SecurityKt.configureSecurity
      - com.bagaspardanailham.bpiktorplayground.RoutingKt.configureRouting
